### PR TITLE
Add proposal and request queues

### PR DESCRIPTION
**Pull request by Vegter**
Resolves issue #5

Also, add flake8 for code quality checking

### CODE REVIEW

**Comment by dolhuis** [comment]
What is the place of this project in the set-up. Currently it looks like only instantiating a docker for RabbitMQ, and one off creation of the workflow queues.

Could this be incorporated in the GOB-Workflow project?

**Comment by Vegter** [comment]
Could be, but actually it is only needed when running GOB locally. I am OK with another setup if this is more logical.

**Comment by dolhuis** [comment]
>  it is only needed when running GOB locally

Ah. I can work with that. Shall I make it an addition to GOB Workflow for the case one is running it locally?

**Comment by Vegter** [comment]
Good idea!

**Pull request closed without merging**
